spring:
  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true  # JPA로 스키마 만든 뒤 data1.sql 실행
  security:
    oauth2:
      client:
        registration:
          google:
            scope: openid, profile, email
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            user-name-attribute: email

server:
  port: 8080
