spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update           # 학습/시험 중엔 update, 운영 전환 시 validate 권장
    properties:
      hibernate:
        format_sql: true

  thymeleaf:
    cache: true

logging:
  level:
    org.hibernate.SQL: warn

server:
  forward-headers-strategy: native


  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            user-name-attribute: email
